### ISSUE TITLE
Handling config mismatches across networks

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#1617] opened 2023-11-15 13:08 UTC
While we have +2/3rds agreement on consensus parameters, there's no real way to know whether one's node is misconfigured in a meaningful way (by way of its `config.toml`) relative to the rest of the network.

Mismatches in the following kinds of parameters, for example, can result in unexpected behaviour across networks:

- Consensus timeouts
- Mempool configuration

Without resorting to turning those config parameters into consensus parameters, what other approaches are there to dealing with this problem?

One option is to share certain config options across the network and simply emit a warning log for operators if a discrepancy is found.

**Comment by melekes** [comment] 2023-11-15 13:12
https://github.com/cometbft/cometbft/discussions/1093 How to speed up diagnosis of chain execution problems when the root cause is inconsistent config

**Comment by lasarojc** [comment] 2023-11-15 13:12
Another option would be to include CometBFT transactions, which operate on the CometBFT state machine itself. That is, a block would include Comet transactions and app transactions. Consensus parameters and validator set changes are a form of Comet transactions, but they are not flexible and including more types of Comet transactions is a hard thing today.

**Comment by melekes** [comment] 2024-06-13 07:01
Closing in favor of https://github.com/cometbft/cometbft/issues/2829

**Closed by melekes** 2024-06-13 07:01 UTC
Labels: enhancement, config
