### ISSUE TITLE
Node panics with SIGSEGV when restoring from an atomic disk snapshot

### ISSUE THREAD

**Issue by hubert-da** [cometbft/cometbft#3140] opened 2024-05-28 12:03 UTC
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): 0.37.2

**Have you tried the latest version**: no (checked, however, if the code has changed)

**ABCI app** (name for built-in, URL for self-written if it's publicly available): closed-source (based on kvstore)

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux

### What happened?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xd3b7bf]
```

(during restoring from an atomic disk snapshot)

### What did you expect to happen?

Normal operation.

### How to reproduce it

Recover a node from an atomic disk snapshot from the past, e.g., AWS EBS backup.

### Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xd3b7bf]

goroutine 1 [running]:
github.com/cometbft/cometbft/state.execBlockOnProxyApp({0x1321ac8?, 0xc0003dd0a0}, {0x13275e0, 0xc00305a060}, 0x0, {0x1329098, 0xc000010f18}, 0xc00088bd40?)
	github.com/cometbft/cometbft@v0.37.2/state/execution.go:331 +0xdf
github.com/cometbft/cometbft/state.ExecCommitBlock({0x13275e0, 0xc00305a060}, 0x0, {0x1321ac8, 0xc0003dd0a0}, {0x1329098?, 0xc000010f18?}, 0xc0000a80d8?)
	github.com/cometbft/cometbft@v0.37.2/state/execution.go:612 +0x67
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x1}, {0xc002f5bcd2, 0x6}}, {0xc002f5bcd8, 0x7}, 0x1, 0x255c5e, {{0xc00028b1a0, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.37.2/consensus/replay.go:471 +0x248
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x1}, {0xc002f5bcd2, 0x6}}, {0xc002f5bcd8, 0x7}, 0x1, 0x255c5e, {{0xc00028b1a0, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.37.2/consensus/replay.go:393 +0x45b
github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc000822c40, {0x132a100, 0xc00089c540})
	github.com/cometbft/cometbft@v0.37.2/consensus/replay.go:268 +0x3ca
github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x1}, {0xc002f5bcd2, 0x6}}, {0xc002f5bcd8, 0x7}, 0x1, 0x255c5e, ...}, ...)
	github.com/cometbft/cometbft@v0.37.2/node/node.go:328 +0x198
github.com/cometbft/cometbft/node.NewNode(0xc0000d18c0, {0x131d990, 0xc000326be0}, 0xc0003d5760, {0x1316740, 0xc000010dc8}, 0xc0001d1728?, 0xbb3b25?, 0xc0002ed0e0, {0x1321ac8, ...}, ...)
	github.com/cometbft/cometbft@v0.37.2/node/node.go:778 +0x56d
```

### Anything else we need to know

The nil dereference error seems to happen here: https://github.com/cometbft/cometbft/blob/v0.37.2/state/execution.go#L331, which points to `block` to be the only thing that can be nil (`block.Txs`). This one gets executed by `ExecCommitBlock` in the same file, and that one in turn by [replay.go.replayBlocks](https://github.com/cometbft/cometbft/blob/v0.37.2/consensus/replay.go#L471). This one takes the `block` from the store: `h.store.LoadBlock(i)`.

Note that there are other snapshots (AWS EBS as well as k8s volume ones) that work.

**Comment by hubert-da** [comment] 2024-05-28 15:43
> Could you please provide more context regarding the restore process ? When you say atomic disk snapshot, are you saving the whole disk (that includes the config and data folder)?

Yes, it's the whole disk (including the config and data folders). Is there anything specific you'd like to know in addition to that?

> And when you restore, are you just loading that disk snapshot again and starting cometbft? Are you using the same cometbft binary version that you used when you saved the snapshot?

Yes and yes.

**Comment by andynog** [comment] 2024-05-28 17:13
OK, thanks. Do you stop the cometbft process before taking the snapshot ?

**Comment by hubert-da** [comment] 2024-05-29 09:54
No, the snapshots are atomic, so there should be no reason to stop it, assuming that CometBFT can recover from a crash at any time. Without proper sentry architecture, stopping it would cause downtime for the clients of that node. Additionally, stopping it in Kubernetes would make its container die.

**Comment by andynog** [comment] 2024-05-29 14:49
Thanks @hubert-da for the additional context. 

Concerning the context in the issue description in `Anything else I should know`, if the `block.Txs` is `nil`, I don't think that's the root cause, it wouldn't panic. 

The idea that it would panic in two places when you check the length (`len(block.Txs)`) or when you do a range over it (`for _, tx := range block.Txs`) is not correct, this is safe in Go. 

In the length case you get `0` and in the range logic is also safe because it's nil it's doesn't execute the logic within it. You can see a quick example [here](https://go.dev/play/p/m83YCd4_4lD) 

But we will investigate further or gather more context from other teams. I've checked with some other ops people and they mentioned they tried this in the past and didn't work too well. 

Probably we need to try to reproduce the problem locally so we can do some additional debugging to try to pinpoint the root cause.

**Comment by andynog** [comment] 2024-05-31 15:40
Hi @hubert-da, I've done some local testing, using two VMs and using zfs to create a volume and take snapshots and try to restart the node with the snapshot restore and I couldn't reproduce the problem. I've tried many times and I can't get it to panic. 

I'm wondering if there's another thing in your setup that might be causing this. Again, cometbft is self-resilient that it uses a WAL so it can restore in case of abrupt interruption. But taking a snapshot of a disk, without stopping the service or at least comet getting some signal that something is about to stop might cause undesired behaviors I'd imagine.

**Comment by hubert-da** [comment] 2024-06-03 08:09
@andynog, thanks for looking into this. Do you write to the node/network in the background while taking snapshots?

> Again, cometbft is self-resilient that it uses a WAL so it can restore in case of abrupt interruption. But taking a snapshot of a disk, without stopping the service or at least comet getting some signal that something is about to stop might cause undesired behaviors I'd imagine.

Isn't taking an atomic snapshot more or less equal to an abrupt interruption?

**Comment by melekes** [comment] 2024-06-10 11:26
FYI the node panics because it expects something to be in memory BUT it's `nil`

**Comment by cason** [comment] 2024-06-10 11:47
The problem is that the recovery process blindly trust that the block to be loaded from the block store is present:

https://github.com/cometbft/cometbft/blob/fe45483be36ebfea7e172a3ad949e8fe09a8fd95/consensus/replay.go#L465

This happens because when this is called, we consider the interval of blocks returned to us by the block store:

https://github.com/cometbft/cometbft/blob/fe45483be36ebfea7e172a3ad949e8fe09a8fd95/consensus/replay.go#L284-L300

It will be interesting to understand what interval of blocks is logged when this issue happens.

**Comment by cason** [comment] 2024-06-10 11:49
It is important to note that this behavior also depends on how the application behaves. You mentioned using the `kvstore` application, which is an example that does **not** persist anything to disk.

So there is the possibility that the application is providing to Comet a wrong block height it has already applied (for any reason, not clear from the data provided), so that Comet is trying to access a block the application informs it has applied but it hasn't, or it has but the crash has happened before Comet was aware of that.

In any case, some additional information is a must to reproduce this kind of non-deterministic bug.

**Comment by hubert-da** [comment] 2024-06-13 08:04
@cason 
> It will be interesting to understand what interval of blocks is logged when this issue happens.

```
{"_msg":"ABCI Handshake App Info","hash":null,"height":2417227,"level":"info","module":"consensus","protocol-version":1,"software-version":"1.0.0","ts":"2024-04-30T11:23:52.096146954Z"}
{"_msg":"ABCI Replay Blocks","appHeight":2417227,"level":"info","module":"consensus","stateHeight":2417231,"storeHeight":2417231,"ts":"2024-04-30T11:23:52.096157724Z"}
{"_msg":"Applying block","height":2417228,"level":"info","module":"consensus","ts":"2024-04-30T11:23:52.096165344Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xd3b7bf]
```

> You mentioned using the kvstore application, which is an example that does not persist anything to disk.

Our application took the persistent version of the kvstore as a template (i.e., we pass the Go LevelDB instance). The application state we store is rather minor. However, we persist the last block height, for example. I will take a closer look at that, thanks.

**Comment by cason** [comment] 2024-06-13 09:48
Thank you for the extended log.

I realized that we don't print the `storeBlockBase := h.store.Base()`. Would you mind to change the code to also print this information?

What appears to me now is that for some reason the block store does not have the block for height `2417228`, which is the next height the application expect to. We don't actually check that in the replay code because it is assume that, if the application has persisted up to height `X`, then all blocks from `X+1` are in the block store.

So another check to be performed is on the application side. One of the returns of the `Commit` ABCI call is `retainHeight`. We prune the block store up to the `retainHeight`. One explanation here is that the application has returned a height which is larger than `2417227`, the last height it has applied and persisted. This would be an application misbehavior.

**Comment by hubert-da** [comment] 2024-06-13 15:28
> I realized that we don't print the storeBlockBase := h.store.Base(). Would you mind to change the code to also print this information?

This would mean updating the CometBFT core. We don't plan on updating as well as propagating it to an environment where we recover from snapshots soon. But I can check with others.

> One explanation here is that the application has returned a height which is larger than 2417227, the last height it has applied and persisted.

That should not be the case because we have the following check (same as the `kvstore` app):
```
if app.RetainBlocks > 0 && app.state.Height >= app.RetainBlocks {
		resp.RetainHeight = app.state.Height - app.RetainBlocks + 1
}
```

**Comment by cason** [comment] 2024-06-19 14:01
We really need a way to reproduce this using test units.

**Comment by melekes** [comment] 2024-09-05 06:10
Without a straightforward way to replicate the issue, it isn’t easy to proceed with further investigation.

Given this, we are going to close the issue for now. However, if you can provide additional information or steps to help us reproduce the issue, please feel free to reopen it; we’ll be happy to take another look.

Thank you again for your understanding and support.

**Closed by melekes** 2024-09-05 06:10 UTC
Labels: bug, needs-triage, needs-information
