### ISSUE TITLE
P2P Connection does not support secp256k1 key type?

### ISSUE THREAD

**Issue by anznwu** [cometbft/cometbft#1202] opened 2023-08-03 01:01 UTC
https://github.com/cometbft/cometbft/blob/9480769d2102ada6197a21dcd1c4ba4654ab835b/p2p/conn/secret_connection.go#L169

I've set up 2 nodes' configs with secp256k1 keys.
But I'm getting following error log while running node 2 which is trying to connect to node 1 as a peer.
```
E[2023-08-03|09:10:16.792] Error dialing peer                           module=p2p err="auth failure: secret conn failed: expected ed25519 pubkey, got secp256k1.PubKey"
```
When I commented out the place where such error is catching(secret_connection.go lines 168~170), p2p connection is made successfully!

So, should the code be upgraded so that it reflects which algorithm is used? ed25519 or secp256k1?

**Comment by brennanjl** [comment] 2023-08-10 21:18
Hey, did you end up figuring this out?

We are looking to use secp256k1 key types for our validators, wondering if you have any insights on that.

**Comment by alijnmerchant21** [comment] 2023-08-14 14:19
Hey @anznwu thanks for reporting this issue. I'll try reproduce and revert back.

**Comment by cason** [comment] 2023-08-16 16:23
> When I commented out the place where such error is catching(secret_connection.go lines 168~170), p2p connection is made successfully!

Yes, it probably works. The problem is that, in this case, I suspect that the node with the updated code will only be able to connect to other nodes running the same code. Namely, a node using this key can only establish connections with other nodes using the same key type.

**Comment by adizere** [comment] 2023-08-29 14:36
Will close optimistically, hoping the original question was fixed in the meantime. We can continue conversations here also: https://github.com/cometbft/cometbft/discussions/1228

**Closed by adizere** 2023-08-29 14:36 UTC
