### ISSUE TITLE
Fast sync gets stuck if there's not many peers because `requestRoutine` in pool requests blocks out of order

### ISSUE THREAD

**Issue by musalbas** [cometbft/cometbft#1283] opened 2023-08-26 18:52 UTC
Fast sync gets stuck (or proceeds very slowly) because `requestRoutine` in pool requests blocks in a different order because requesters get made asynchronously by `makeNextRequester` (https://github.com/tendermint/tendermint/blob/main/blockchain/v0/pool.go#L375C24-L375C41). This causes fast sync to get stuck if there's not many peers, because `maxPendingRequestsPerPeer` is 20.

Sample debugging logs from manually added debugging prints:
```
debug0: making next requester for  256513
debug0: making next requester for  256514
debug0: making next requester for  256515
debug0: making next requester for  256516
debug0: making next requester for  256517
debug0: making next requester for  256518
debug0: making next requester for  256519
debug0: making next requester for  256520
debug0: making next requester for  256521
debug0: making next requester for  256522
debug0: making next requester for  256523
debug0: making next requester for  256524
debug0: making next requester for  256525
debug0: making next requester for  256526
debug0: making next requester for  256527
debug0: making next requester for  256528
debug0: making next requester for  256529
debug0: bpr making request for  256529
debug0: bpr making request for  256521
debug0: bpr making request for  256514
debug0: bpr making request for  256516
debug0: bpr making request for  256517
debug0: bpr making request for  256515
debug0: bpr making request for  256518
debug0: bpr making request for  256527
debug0: bpr making request for  256519
debug0: bpr making request for  256520
debug0: bpr making request for  256522
debug0: bpr making request for  256513
debug0: bpr making request for  256523
debug0: bpr making request for  256524
debug0: bpr making request for  256525
debug0: bpr making request for  256526
```

Increasing `maxPendingRequestsPerPeer` to 600 fixes the problem (though obviously not a proper fix). edit: still having issues with increasing it to that param, unless I also decrease maxTotalRequesters significantly

**Comment by musalbas** [comment] 2023-08-26 18:55
related: maybe root cause of https://github.com/cosmos/gaia/issues/873?

**Comment by cason** [comment] 2023-09-04 13:26
To which version of CometBFT/Tendermint Core this code and those messages refer?

**Comment by cason** [comment] 2023-09-04 13:34
Ok, the report is of low performance, or block sync fails in retrieving blocks from its peers?

From the messages you posted, it looks like that the assignment of each peer should handle each block/height was not the best one, leading to a situation at which blocks are received completely out of order. But, again, from the provided information, it appears that all blocks are eventually retrieved, is that correct?

**Comment by cason** [comment] 2023-09-04 13:46
I would need more information about the execution environment in order to reproduce the reported the scenario.

It can be indeed a bug in the operation of block sync, it can also be about tuning some parameters, but it can also be the case that the peers your node is interacting with are particularly slow (which would explain why the progress relies on timeouts).

**Comment by musalbas** [comment] 2023-09-04 13:57
I'm reasonably sure it's not because my peers are slow, because when running CometBFT with `--log_level debug`, I observed that my node was constantly receiving blocks from other peers, but they never got committed due to being out of order, and my `RecvRate` with other peers was maxed out in `/net_info`. This occurred on a devnet with 3 peers, and it seemed to only occur after around 200,000 blocks. I'm not sure why this only occurred after a certain number of blocks, though. This can be replicated currently on the [Celestia arabica-9 devnet](https://docs.celestia.org/nodes/arabica-devnet/).

**Comment by cason** [comment] 2023-09-04 15:07
Can you check whether the version of the code you are running includes this fix?

https://github.com/tendermint/tendermint/pull/9518/

**Comment by musalbas** [comment] 2023-09-04 15:10
Yes, it does seem to have that fix: https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/blockchain/v0/pool.go

**Comment by cason** [comment] 2023-09-04 15:18
We will try to reproduce the reported scenario and provide a more grounded feedback.

**Comment by alijnmerchant21** [comment] 2023-09-15 12:03
Hey @musalbas do you still see this issue? I tried to replicate the issue by following your [docs](https://docs.celestia.org/nodes/arabica-devnet) - but it worked for me okay. Can you pinpoint changes you might have made like - `config` changes or any other changes? Thanks!

**Comment by musalbas** [comment] 2023-09-15 12:10
Hi @alijnmerchant21, those docs point to arabica-10 which is a new network that was recently launched. The issue occurred on arabica-9, docs here: https://docs.celestia.org/arabica-9/. I didn't make any changes to the config when I last tried a few weeks ago.

**Comment by alijnmerchant21** [comment] 2023-09-15 12:15
Ok, thanks. In my first pass, I did not see an issue. I'll try it again next week. Thank you for your patience Mustafa :)

**Comment by melekes** [comment] 2024-03-04 07:54
Should be fixed by https://github.com/cometbft/cometbft/pull/2467. I'm going to backport this to `v0.38.x`.

@musalbas thanks for reporting ❤️ and sorry it took us so long to fix

**Closed** 2024-03-11 04:59 UTC
Labels: bug, block-sync
