### ISSUE TITLE
Stop overwriting msgBytes when receiving data

### ISSUE THREAD

**Issue by evan-forbes** [cometbft/cometbft#3237] opened 2024-06-11 06:02 UTC
Currently, when we receive a packet we are reusing the same slice to avoid extra allocations. That's nice, however it results in overwriting the message if we receive packets fast enough.

https://github.com/cometbft/cometbft/blob/2dd5209177270fde125c71aeedda9819046f92f0/p2p/conn/connection.go#L891-L898

This might explain https://github.com/celestiaorg/celestia-core/issues/1138, which has been confusing us for while.

This problem gets way worse when we buffer our received messages to the point of stopping consensus, because buffering our received messages allows us to process messages async, which both gives them time to be overwritten and receive message faster since we stop blocking the tcp connection.

**Comment by cason** [comment] 2024-06-11 06:21
Not sure if I understood. We indeed re-use the same receive buffer for all messages coming from all channels.

This is mainly because messages are proto encoded, so the buffer (raw message) used to produce a specific message object, which is supposed to copy data from the input array/buffer, not refer to parts of it.

**Comment by cason** [comment] 2024-06-11 06:21
In any case, I would like to see a way to produce this scenario while using standard Comet (plus some patches, if it is the case).

**Comment by evan-forbes** [comment] 2024-06-11 06:28
this is mainly problematic if we do https://github.com/cometbft/cometbft/pull/3230, which passes that slice of bytes to a queue to be unmarshalled.

**Comment by cason** [comment] 2024-06-11 11:52
I think this issue is relevant if we pursue the goal of taking the unmarshalling of received messages from the main receive loop of p2p connections, like proposed in #3209.

**Comment by evan-forbes** [comment] 2024-06-11 13:03
> I think this issue is relevant if we pursue the goal of taking the unmarshalling of received messages from the main receive loop of p2p connections, like proposed 

yeah exactly! this is blocking #3230

**Comment by ValarDragon** [comment] 2024-06-12 17:00
So in my pr on the topic I just took a copy for doing that, since it's in its own goroutine. 

I kind of think short term we just take a copy before handing of to mconn.onreceive.

Medium / longer term; we swap out secretconn and use something else with smarter buffering and frame size logic

**Comment by cason** [comment] 2024-07-10 08:24
For context, this is not a bug.

But making a copy of the received bytes may be necessary if we start unmarshalling received messages in parallel.

**Comment by melekes** [comment] 2024-09-05 06:16
Just to clarify, this doesn't appear to be a bug or feature since it only becomes relevant when we start unmarshalling received messages in parallel.

I'd suggest closing this issue for now, but keeping it in mind when implementing [this PR](https://github.com/cometbft/cometbft/pull/3230) or smth similar. However, please feel free to reopen it if I’ve misunderstood anything.

**Closed by melekes** 2024-09-05 06:16 UTC
Labels: enhancement, p2p, low-priority
