### ISSUE TITLE
why not execute the block after proposer prepare it?

### ISSUE THREAD

**Issue by kimroniny** [cometbft/cometbft#622] opened 2023-03-30 15:32 UTC
### Discussed in https://github.com/cometbft/cometbft/discussions/621

<div type='discussions-op-text'>

<sup>Originally posted by **kimroniny** March 30, 2023</sup>
in cometBFT, a block(assume height=10) is executed in commit phase. 

It means that the app hash which calculated by the state in the block(height=10) can only be included in the block(height=11).

So, WHY not the proposer execute a block after prepareing it and before broadcasting it to other validators ???

In this way, the proposer can include the apphash in the current block and the apphash will be signed by validators after consensus.

</div>

**Comment by sergio-mena** [comment] 2023-03-30 17:10
Duplicate of #446

**Closed by sergio-mena** 2023-03-30 17:10 UTC
