### ISSUE TITLE
Consensus Failure error when trying to sign using remote signer

### ISSUE THREAD

**Issue by frangrech** [cometbft/cometbft#2711] opened 2024-04-03 15:21 UTC
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): v0.38.5 (as part of palomad v1.13.0)

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/palomachain/paloma v1.13.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
- **Install tools**: go version go1.21.4 linux/amd64; but seeing the same behaviour if running pre-built palomad binary
- **Others**: tmkms on another machine, v0.14.0

**node command runtime flags**: start

### Config
Nothing particularly different from default, other than the node being connected to a remote signer, and having metrics and state sync enabled.

### What happened?
Whenever the validator attempts to sign a block using a remote signer (tmkms v0.14.0), we get a consensus failure error, regardless of which block it tries to sign. The node stops syncing completely afterwards. Restarting the node causes it to sync back up to the latest block height, until it tries to sign again and fails again.

### What did you expect to happen?
The validator signs blocks normally.

### How to reproduce it
Try to sign a block using remote tmkms.

### Logs
```
2:59PM ERR CONSENSUS FAILURE!!! err="non-recoverable error when signing vote (15385390/1)" module=consensus stack="goroutine 139403 [running]:
runtime/debug.Stack()
    /opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x46
panic({0x2d03080?, 0xc0b5748830?})
    /opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x21f
github.com/cometbft/cometbft/consensus.(*State).signVote(0xc000aaca80, 0x2, {0xc03d3b9360, 0x20, 0x20}, {0xe0eb5c?, {0xc03d3b9380?, 0xc054dc92ec?, 0x3035160?}}, 0xc0aff57a40)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2388 +0x639
github.com/cometbft/cometbft/consensus.(*State).signAddVote(0xc000aaca80, 0x1?, {0xc03d3b9360, 0x20, 0x20}, {0x1?, {0xc03d3b9380?, 0xc0fd083a60?, 0x20?}}, 0xc0aff57a40)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2439 +0x212
github.com/cometbft/cometbft/consensus.(*State).enterPrecommit(0xc000aaca80, 0xeac32e, 0x1)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1536 +0x1337
github.com/cometbft/cometbft/consensus.(*State).addVote(0xc000aaca80, 0xc1677dc270, {0xc00675e120, 0x28})
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2296 +0x186f
github.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc000aaca80, 0xc1677dc270, {0xc00675e120?, 0xc054dc9c08?})
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2056 +0x26
github.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc000aaca80, {{0x3c0ebc0, 0xc0b4f8ebc8}, {0xc00675e120, 0x28}})
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x3ce
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc000aaca80, 0x0)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:835 +0x3d1
created by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 334
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0x10c"
2:59PM INF service stop impl=baseWAL module=consensus msg="Stopping baseWAL service" wal=/home/validator/.paloma/data/cs.wal/wal
2:59PM INF service stop impl=Group module=consensus msg="Stopping Group service" wal=/home/validator/.paloma/data/cs.wal/wal
```

### `dump_consensus_state` output
[consensus_dump.json](https://github.com/cometbft/cometbft/files/14854480/consensus_dump.json)

### Anything else we need to know
We have not tried signing without a remote signer, but we seem the only ones with this particular issue since the upgrade.

**Comment by cason** [comment] 2024-04-04 15:05
Hey, unfortunately this version does not provide the error that is non-recoverable:

https://github.com/cometbft/cometbft/blob/2cd0d1a33cdb6a2c76e6e162d892624492c26290/consensus/state.go#L2386-L2389

The latest v0.38.x release, v0.38.6, contains the error that produced the panic:

https://github.com/cometbft/cometbft/blob/151956229550209d8a1946a4b02a8ed5c4069d78/consensus/state.go#L2396-L2399

Do you mind testing with v0.38.6 or manually changing the code in order to include the error returned by `SignAndCheckVote`?

In any case, the non-recoverable errors produced by this method are typically related to the absence of vote extensions: https://github.com/cometbft/cometbft/blob/dc4590e1c874eda7d760d14e39f656b3e2622cdf/types/vote.go#L430-L443

The most likely case is that votes extensions are enabled, but they were not produced by the application.

**Comment by taariq** [comment] 2024-04-05 23:01
Thank you for the review @cason. We forgot to share our consensus params for this ticket. They are here and show that vote extensions are disabled.

````
{"jsonrpc":"2.0","id":-1,"result":{"block_height":"15422849","consensus_params":{"block":{"max_bytes":"22020096","max_gas":"-1"},"evidence":{"max_age_num_blocks":"100000","max_age_duration":"172800000000000","max_bytes":"1048576"},"validator":{"pub_key_types":["ed25519"]},"version":{"app":"0"},"abci":{"vote_extensions_enable_height":"0"}}}}
```

We are going to attempt to upgrade to v38.6. Not sure whether that helps, but we welcome your review/thoughts.

**Comment by cason** [comment] 2024-04-08 19:59
> We are going to attempt to upgrade to v38.6. Not sure whether that helps, but we welcome your review/thoughts.

This will definitely make the error message more detailed.

**Comment by cason** [comment] 2024-04-08 20:14
I am afraid this is related to: https://github.com/cometbft/cometbft/issues/2439

**Comment by cason** [comment] 2024-04-08 20:19
But this should be fixed on the TMKMS side: https://github.com/iqlusioninc/tmkms/pull/890

**Comment by cason** [comment] 2024-04-08 20:23
>  We are going to attempt to upgrade to v38.6. Not sure whether that helps, but we welcome your review/thoughts.

I've just checked both v38.5 and v38.6. In the latter, the test unit introduced by the PR above passes. In the former, it does not.

So please update to v38.6 and check if the problem happens again.

**Comment by taariq** [comment] 2024-04-08 21:04
> 
> So please update to v38.6 and check if the problem happens again.

Yep. This is our path ahead. Thank you for confirming the test on the two versions. Cheers.

**Comment by frangrech** [comment] 2024-04-22 16:26
Hello again, following the palomad v1.13.3 update which uses cometbft v0.38.6, we are getting this error when trying to sign with tmkms v0.14.0:
```
3:02PM ERR CONSENSUS FAILURE!!! err="non-recoverable error when signing vote Vote{0:1734D2D87EDB 15862629/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 2D4F6853AF7D 84DEFB4913EF 000000000000 @ 2024-04-22T15:02:42.778456158Z}: extensions must be present IFF vote is a non-nil Precommit; extension signature: " module=consensus stack="goroutine 18204 [running]:
runtime/debug.Stack()
    /home/paloma/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/runtime/debug/stack.go:24 +0x5e
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:801 +0x46
panic({0x3017fa0?, 0xc0b75e47a0?})
    /home/paloma/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/cometbft/cometbft/consensus.(*State).signVote(0xc00668c008, 0x2, {0xc03202c740, 0x20, 0x20}, {0xe436a8?, {0xc03202c760?, 0xc005be72bc?, 0x160?}}, 0xc06c0cc3c0)
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2398 +0x61e
github.com/cometbft/cometbft/consensus.(*State).signAddVote(0xc00668c008, 0x2, {0xc03202c740, 0x20, 0x20}, {0xf1b828?, {0xc03202c760?, 0xc078999460?, 0x20?}}, 0xc06c0cc3c0)
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2449 +0x215
github.com/cometbft/cometbft/consensus.(*State).enterPrecommit(0xc00668c008, 0xf20b65, 0x0)
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1537 +0x12f7
github.com/cometbft/cometbft/consensus.(*State).addVote(0xc00668c008, 0xc09597be10, {0xc0015cbb90, 0x28})
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2306 +0x17cf
github.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc00668c008, 0xc09597be10, {0xc0015cbb90?, 0x0?})
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2066 +0x26
github.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00668c008, {{0x46be8e0, 0xc04dc9a318}, {0xc0015cbb90, 0x28}})
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:929 +0x39c
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00668c008, 0x0)
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:836 +0x3f1
created by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 302
    /home/paloma/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:398 +0x10c"
```

**Comment by cason** [comment] 2024-04-22 16:35
This is a Precommit vote for a non-nil value, for which it is expected a vote extension. But the signer is returning a vote where the vote extension signature is missing.

**Comment by cason** [comment] 2024-04-22 16:48
I assume vote extensions are disabled, aren't them? If so, the problem is the same as reported in the issue above mentioned.

**Comment by taariq** [comment] 2024-04-22 17:25
> I assume vote extensions are disabled, aren't them? If so, the problem is the same as reported in the issue above mentioned.

Yes. as per https://github.com/cometbft/cometbft/issues/2711#issuecomment-2040741332 vote extensions are disabled.

**Comment by cason** [comment] 2024-04-23 17:38
Great, please feel free to close the issue if you think it is solved.

We might consider documenting this solution somewhere, as I am afraid that the same issue will be reported again...

**Closed** 2024-04-23 20:42 UTC
Labels: privval, needs-information

**Comment by scirner22** [comment] 2024-06-29 02:41
I have a 4 node testnet that saw this problem. How do you actually recover the chain after this? It seems like I need the validators to submit new signatures on the problem block.
