### ISSUE TITLE
Block Proposal Failure（proposal block parts exceeds maximum block bytes）

### ISSUE THREAD

**Issue by lx-xiang** [cometbft/cometbft#1675] opened 2023-11-22 03:21 UTC
## Environment Information

- Cometbft Version: v0.37.2
- Cosmos Sdk Version: v0.47.3
- Cosmos Mempool Used: SenderNonceMempool
- Number of Validator: 3

## Err log
`ERR failed to process message err="total size of proposal block parts exceeds maximum block bytes (2097374 > 2097152)" height=2771 module=consensus msg_type=*consensus.BlockPartMessage peer=b9018b4260f19b5e0e8b0429c603d4156e6c2702 round=259`
`ERR failed to process message err="total size of proposal block parts exceeds maximum block bytes (2097354 > 2097152)" height=2771 module=consensus msg_type=*consensus.BlockPartMessage peer=1af9376873ae9bfa5cbb33a954f344afe96d55c6 round=260`

https://github.com/cometbft/cometbft/blob/v0.37.2/consensus/state.go#L1931

## Consensus Params
for all validators are configured as follows
`{"jsonrpc":"2.0","id":-1,"result":{"block_height":"2770","consensus_params":{"block":{"max_bytes":"2097152","max_gas":"-1"},"evidence":{"max_age_num_blocks":"100000","max_age_duration":"172800000000000","max_bytes":"1048576"},"validator":{"pub_key_types":["ed25519"]},"version":{"app":"0"}}}}`
`{"jsonrpc":"2.0","id":-1,"result":{"block_height":"2771","consensus_params":{"block":{"max_bytes":"2097152","max_gas":"-1"},"evidence":{"max_age_num_blocks":"100000","max_age_duration":"172800000000000","max_bytes":"1048576"},"validator":{"pub_key_types":["ed25519"]},"version":{"app":"0"}}}}`

**Comment by andynog** [comment] 2023-11-22 19:35
Hi @lx-xiang, thanks for reporting this. I believe the message in the log is just letting you know that the `max_bytes` configured might not be enough to accomodate the total size of proposal block parts, so doesn't seem to be a bug. But I'm not sure how you are testing/running this so I can't tell if it's just a matter of increasing that parameter value. 

Also, the `SenderNonceMempool` that you've mentioned in this issue, it is something implemented at the `cosmos-sdk` level. If you still think this is a bug, have you tried to open an issue in their repo?
https://github.com/cosmos/cosmos-sdk/blob/main/types/mempool/sender_nonce.go

**Comment by lx-xiang** [comment] 2023-11-23 02:01
I discovered that in the cosmos-sdk DefaultProposalHandler, the size is determined by the MaxTxBytes field of RequestPrepareProposal. I suspect that when CometBFT calls cosmos-sdk, it may be providing an incorrect MaxTxBytes

**Comment by lx-xiang** [comment] 2023-11-23 13:21
I discovered that the inconsistency in byte calculations for tx between Cosmos SDK and CometBFT is causing the issue. I have submitted a pull request to Cosmos SDK.
ref: https://github.com/cosmos/cosmos-sdk/pull/18551

**Comment by andynog** [comment] 2023-11-30 19:03
Thanks for investigating, @lx-xiang. I noticed that the SDK has merged your [PR](https://github.com/cosmos/cosmos-sdk/pull/18551). Please let us know if you think the issue is resolved after testing, so we can close it.

**Comment by lasarojc** [comment] 2023-12-01 09:38
Pls don't close yet. We should consider his PR on CometBFT for merge.

**Comment by lasarojc** [comment] 2023-12-05 22:43
Before this fix, if the app returns a slightly oversized set of transactions, an invalid block would be created and proposed, only being caught by the receiver with the following message.

`failed to process message ... msg_type=*consensus.BlockPartMessage err="total size of proposal block parts exceeds maximum block bytes`

After the fix, even slightly oversized set of transactions will be caught by the proposer and result in 
`CONSENSUS FAILURE!!!  module=consensus err="transaction data size exceeds maximum "`

cc: @alexanderbez

**Closed** 2023-12-05 22:43 UTC
Labels: consensus, mempool
